### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by JinDDung2** [f-lab-edu/givemeticon#44]
## 목표

> 프로젝트 중반 시기에 코드 품질을 위한 리팩토링

## 요구사항
- [x] 패키지 리팩토링
- [x] api 공통 응답을 위한 ApiResponse fail 만들기 [#15  ]
- [x] AuthIntercepter → 필터 순서 지정해보기 [#13 ]
- [x] 테스트 환경에는 인터셉터를 적용하지 않게 하라는 로직을 인터셉터에 작성하기 [#13 ]
- [x] Select SQL 에 “*” 사용을 지양하라.
- [x] bradnService에 있는 toDto를 brandDto 클래스에 만들어라. [#30 ]
- [x] categoryService → 빈 리시트라면 예외처리가 아니라 빈 리스트를 보내라. [#31  ]

## 참고자료
[7 Reasons Why Using SELECT * FROM TABLE in SQL Query Is a Bad Idea](https://dzone.com/articles/why-you-should-not-use-select-in-sql-query-1)
